### ISSUE TITLE
Repack Feature

### ISSUE THREAD

**Issue by Riderick** [Yagotzirck/erad_ripper#1]
Is there any possibility to reimport the pictures into MAIN.RID ?? The idea is to translate the game to some language.

Thanks in advance.

**Comment by Yagotzirck** [comment]
If you want to translate it, all the strings are embedded inside the game's exe (aside from some graphics inside the PICTURES folder), so you'd better try to edit them with a hex editor or something similar in order to accomplish your goal.

Having said that, it should be feasible, albeit with some constraints:

- Using the same palette used by the original graphics (if I remember correctly, all the palettes share the first 100-something colors, so it's advisable to stick with those; otherwise, the changed graphics would display fine only with a specific mission set)

- Sticking with the original image's width and height for each modification (*maybe* this can be circumvented, but I'm not too sure about it and it would increase complexity either way)

- Saving the modified pictures to be imported back in the archive in a simple lossless format such as .tga or .bmp (png is a no-no)

I'm quite busy lately though, so if this is ever going to happen it won't be anytime soon; I'll probably consider the request at some point though.

**Comment by Riderick** [comment]
Hi! Thanks for your quick response... I haven't attempt yet to search to all the strings the game has... I thank you for the information.

I was interested in the images, so that I was looking into that... 

I found an alternative method.. and I managed to "understood" that the images are in raw format in MAIN.RID so... I ripped them with another utility in RAW format (forgetting about the palette thing)... and compared it with what it has in MAIN.RID to know they are the same...

(Sorry for my English) But the thing is....  that i found that "at least"... the utility JASC Paint Shop Pro 4.15 managed to open, edit and save some of the 8 bits RAW files (maybe it can edit all of them as well) **respecting its original internal structure** (have tryed other "modern" utilites but changes it internal structure and they were of no use since it loads bad in-game because of the palette (that is what I believe)...

So.. with HxD (An Hex editor) I imported some edited RAW files inside MAIN.RID replacing the original ones...

I Load the game and the images loads fine (Good!)...

- It loads fine with the same internal structure + the palette the game uses (On MAIN.RID Untouched);

- It loads bad with another internal structure = it loads with garbage color pixels).

I hope i managed to explain it well.

The bad thing on this method is that you have to edit them on grayscale since I don't use the palette in the editor... you have no colors... It's possible to edit them of course.

- What I don't know if it's possible to Load the Palette into this editor... to edit it in color... and then remove the palette info and keep the same internal structure on the file... So that i could import it into MAIN.RID in RAW format...

I don't know if that is possible....

Thank you in advance.

**Comment by Yagotzirck** [comment]
I don't have any experience with Paint Shop Pro so I can't help you with the palette import thing, sorry about that.
Refer to the method I explained in my previous post; if you manage to save your changes in a simple file format with any program while sticking to the original game's palette, it should be trivial to convert the image back to raw indices with a custom tool (I don't know if you have any programming experience though).
